services:
  static_web:
    image: nginx:alpine
    container_name: static_web
    restart: unless-stopped
    volumes:
      - ./html:/usr/share/nginx/html:ro
    networks:
      - shared-network

networks:
  shared-network:
    external: true